/**
 * AuthKey.io SMS Service
 * Handles OTP sending and verification via AuthKey.io API
 */

const https = require('https');
const http = require('http');

class AuthKeyService {
  constructor() {
    this.authKey = process.env.AUTHKEY_API_KEY;
    this.senderId = process.env.AUTHKEY_SENDER_ID;
    this.templateId = process.env.AUTHKEY_TEMPLATE_ID;
    this.peId = process.env.AUTHKEY_PE_ID; // DLT Entity ID for India
    this.baseUrl = 'console.authkey.io';
  }

  /**
   * Generate 6-digit OTP
   */
  generateOTP() {
    return Math.floor(100000 + Math.random() * 900000).toString();
  }

  /**
   * Send OTP via SMS using AuthKey.io 2FA API
   * @param {string} mobile - Mobile number without country code
   * @param {string} countryCode - Country code (e.g., '91' for India)
   * @returns {Promise<{success: boolean, logId: string, otp: string, message: string}>}
   */
  async sendOTP(mobile, countryCode = '91') {
    return new Promise((resolve, reject) => {
      if (!this.authKey) {
        return reject(new Error('AuthKey API key not configured'));
      }

      if (!this.templateId) {
        return reject(new Error('AuthKey Template ID not configured'));
      }

      // Build API URL for 2FA
      const path = `/restapi/request.php?authkey=${this.authKey}&mobile=${mobile}&country_code=${countryCode}&sid=${this.templateId}`;

      console.log('📱 Sending OTP via AuthKey.io');
      console.log('   Mobile:', `+${countryCode} ${mobile}`);
      console.log('   Template ID:', this.templateId);

      const options = {
        hostname: this.baseUrl,
        port: 443,
        path: path,
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        }
      };

      const req = https.request(options, (res) => {
        let data = '';

        res.on('data', (chunk) => {
          data += chunk;
        });

        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            
            console.log('✅ AuthKey.io Response:', response);

            if (response.LogID) {
              // Success - OTP sent
              resolve({
                success: true,
                logId: response.LogID,
                message: response.Message || 'OTP sent successfully',
                // Note: Actual OTP is generated by AuthKey.io, not returned
              });
            } else {
              // Error response
              reject(new Error(response.Message || 'Failed to send OTP'));
            }
          } catch (error) {
            console.error('❌ Failed to parse AuthKey.io response:', error);
            reject(new Error('Invalid response from SMS service'));
          }
        });
      });

      req.on('error', (error) => {
        console.error('❌ AuthKey.io API Error:', error);
        reject(error);
      });

      req.end();
    });
  }

  /**
   * Send OTP via SMS using POST API with custom message
   * @param {string} mobile - Mobile number without country code
   * @param {string} countryCode - Country code
   * @param {string} message - SMS message content
   * @returns {Promise<{success: boolean, logId: string, message: string}>}
   */
  async sendCustomSMS(mobile, countryCode, message) {
    return new Promise((resolve, reject) => {
      if (!this.authKey) {
        return reject(new Error('AuthKey API key not configured'));
      }

      const postData = JSON.stringify({
        country_code: countryCode,
        mobile: mobile,
        sms: message,
        sender: this.senderId,
        pe_id: this.peId,
        template_id: this.templateId
      });

      const options = {
        hostname: this.baseUrl,
        port: 443,
        path: '/restapi/requestjson.php',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Basic ${Buffer.from(this.authKey).toString('base64')}`,
          'Content-Length': postData.length
        }
      };

      console.log('📱 Sending Custom SMS via AuthKey.io');
      console.log('   Mobile:', `+${countryCode} ${mobile}`);

      const req = https.request(options, (res) => {
        let data = '';

        res.on('data', (chunk) => {
          data += chunk;
        });

        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            console.log('✅ AuthKey.io Response:', response);

            if (response.LogID || response.status === 'success') {
              resolve({
                success: true,
                logId: response.LogID,
                message: response.Message || 'SMS sent successfully'
              });
            } else {
              reject(new Error(response.Message || 'Failed to send SMS'));
            }
          } catch (error) {
            console.error('❌ Failed to parse response:', error);
            reject(new Error('Invalid response from SMS service'));
          }
        });
      });

      req.on('error', (error) => {
        console.error('❌ AuthKey.io API Error:', error);
        reject(error);
      });

      req.write(postData);
      req.end();
    });
  }

  /**
   * Verify OTP using AuthKey.io 2FA Verification API
   * @param {string} logId - LogID received from sendOTP response
   * @param {string} otp - OTP entered by user
   * @param {string} channel - Channel used (SMS/VOICE/EMAIL)
   * @returns {Promise<{success: boolean, message: string}>}
   */
  async verifyOTP(logId, otp, channel = 'SMS') {
    return new Promise((resolve, reject) => {
      if (!this.authKey) {
        return reject(new Error('AuthKey API key not configured'));
      }

      const path = `/api/2fa_verify.php?authkey=${this.authKey}&channel=${channel}&otp=${otp}&logid=${logId}`;

      console.log('🔍 Verifying OTP via AuthKey.io');
      console.log('   LogID:', logId);
      console.log('   OTP:', otp);
      console.log('   Channel:', channel);

      const options = {
        hostname: this.baseUrl,
        port: 443,
        path: path,
        method: 'GET',
        headers: {
          'Content-Type': 'application/json'
        }
      };

      const req = https.request(options, (res) => {
        let data = '';

        res.on('data', (chunk) => {
          data += chunk;
        });

        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            
            console.log('✅ AuthKey.io Verification Response:', response);

            if (response.status === true || response.message === 'Valid OTP') {
              resolve({
                success: true,
                message: 'Valid OTP'
              });
            } else {
              resolve({
                success: false,
                message: response.message || 'Invalid OTP'
              });
            }
          } catch (error) {
            console.error('❌ Failed to parse verification response:', error);
            reject(new Error('Invalid response from verification service'));
          }
        });
      });

      req.on('error', (error) => {
        console.error('❌ AuthKey.io Verification Error:', error);
        reject(error);
      });

      req.end();
    });
  }

  /**
   * Send OTP with template variables
   * @param {string} mobile - Mobile number
   * @param {string} countryCode - Country code
   * @param {string} templateId - Template SID
   * @param {object} variables - Template variables (e.g., {name: 'John', otp: '1234'})
   * @returns {Promise<{success: boolean, logId: string, message: string}>}
   */
  async sendTemplateOTP(mobile, countryCode, templateId, variables = {}) {
    return new Promise((resolve, reject) => {
      if (!this.authKey) {
        return reject(new Error('AuthKey API key not configured'));
      }

      // Build query string with template variables
      const params = new URLSearchParams({
        authkey: this.authKey,
        mobile: mobile,
        country_code: countryCode,
        sid: templateId,
        ...variables
      });

      const path = `/request?${params.toString()}`;

      console.log('📱 Sending Template OTP via AuthKey.io');
      console.log('   Mobile:', `+${countryCode} ${mobile}`);
      console.log('   Template ID:', templateId);
      console.log('   Variables:', variables);

      const options = {
        hostname: 'api.authkey.io',
        port: 443,
        path: path,
        method: 'GET'
      };

      const req = https.request(options, (res) => {
        let data = '';

        res.on('data', (chunk) => {
          data += chunk;
        });

        res.on('end', () => {
          try {
            const response = JSON.parse(data);
            console.log('✅ AuthKey.io Response:', response);

            if (response.LogID) {
              resolve({
                success: true,
                logId: response.LogID,
                message: response.Message || 'OTP sent successfully'
              });
            } else {
              reject(new Error(response.Message || 'Failed to send OTP'));
            }
          } catch (error) {
            console.error('❌ Failed to parse response:', error);
            reject(new Error('Invalid response from SMS service'));
          }
        });
      });

      req.on('error', (error) => {
        console.error('❌ AuthKey.io API Error:', error);
        reject(error);
      });

      req.end();
    });
  }
}

module.exports = new AuthKeyService();
